In [9]:
import pandas as pd

In [10]:
data=pd.read_csv("insurance_pre.csv")

In [11]:
data

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [12]:
data=pd.get_dummies(data,drop_first=True)
data

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [13]:
data.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [14]:
indep=data[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=data[['charges']]

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param={'criterion':['mse','mae','friedman_mse'],'max_features': ['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param,refit=True,verbose=3,n_jobs=-1)
grid.fit(indep,dep)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    6.3s
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:    6.6s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [16]:
result=grid.cv_results_
print("R2,Best result combination{}:".format(grid.best_params_))

R2,Best result combination{'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'}:

In [17]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.016733,0.002446,0.010005,0.004082,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.709719,0.653012,0.691371,0.684701,0.023626,7
1,0.016667,0.002354,0.011672,0.006234,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.625170,0.740752,0.698949,0.688290,0.047784,6
2,0.017902,0.005155,0.007837,0.002089,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.664695,0.719941,0.655434,0.680023,0.028478,9
3,0.018356,0.006258,0.008334,0.002358,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.675324,0.511317,0.692402,0.626348,0.081637,16
4,0.010001,0.000003,0.006670,0.002360,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.673808,0.653116,0.661627,0.662850,0.008492,10
5,0.010004,0.000008,0.006668,0.002350,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.612818,0.688526,0.658256,0.653200,0.031114,13
6,0.061716,0.006241,0.005001,0.000004,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.688055,0.729749,0.656732,0.691512,0.029909,5
7,0.051719,0.004714,0.005006,0.000003,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.688356,0.720409,0.744061,0.717609,0.022828,1
8,0.043374,0.002346,0.005005,0.000005,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.651637,0.519048,0.612247,0.594311,0.055595,17
9,0.033347,0.006233,0.008359,0.004745,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.642586,0.573122,0.489793,0.568500,0.062463,18
10,0.040058,0.007085,0.008336,0.004713,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.609300,0.667124,0.690643,0.655689,0.034178,12
11,0.030696,0.002100,0.003337,0.002359,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.622918,0.721916,0.641687,0.662174,0.042933,11
12,0.015194,0.004099,0.008183,0.002255,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.709167,0.668501,0.702518,0.693396,0.017811,4
13,0.009850,0.000216,0.008337,0.002357,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.706717,0.688684,0.708112,0.701171,0.008848,2
14,0.010007,0.000009,0.006670,0.002358,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.679427,0.688712,0.724936,0.697692,0.019634,3
15,0.014997,0.004082,0.010016,0.000015,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.597120,0.604088,0.677876,0.626361,0.036537,15
16,0.018350,0.002362,0.010000,0.007074,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.681957,0.689604,0.680684,0.684081,0.003939,8
17,0.013337,0.004716,0.003334,0.002358,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.616757,0.607909,0.655652,0.626773,0.020738,14

In [18]:
age=float(input("Age:"))
BMI=float(input("BMI:"))
children=int(input("Children:"))
sex=int(input("Male-1 or Female-0:"))
smoker=int(input("Yes-0 or No-1:"))

Age:35
BMI:25
Children:2
Male-1 or Female-0:0
Yes-0 or No-1:0

In [19]:
Future_charge_prediction=grid.predict([[age,BMI,children,sex,smoker]])
Future_charge_prediction
print("Future Prediction:{}".format(Future_charge_prediction))

Future Prediction:[6402.29135]