In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("insurance_pre.csv")

In [3]:
data

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
data=pd.get_dummies(data,drop_first=True)
data

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
data.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
indep=data[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=data[['charges']]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param={'criterion':['mse','mae','friedman_mse'],'max_features': ['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    3.2s
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:    3.3s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [13]:
y_pred=grid.predict(x_test)

In [14]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.754292050956851

In [15]:
result=grid.cv_results_
print("R2,Best result combination{}:".format(grid.best_params_))

R2,Best result combination{'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'}:

In [16]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010466,0.000000,0.000000,0.000000e+00,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.533684,0.700438,0.646227,0.626783,0.069452,7
1,0.007820,0.002091,0.002336,2.054877e-03,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.591768,0.645083,0.643392,0.626747,0.024744,8
2,0.004999,0.000002,0.003336,2.358988e-03,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.653901,0.616412,0.689766,0.653360,0.029949,2
3,0.005002,0.000001,0.003335,2.357920e-03,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.373508,0.555843,0.586536,0.505296,0.094027,18
4,0.005014,0.000011,0.005005,5.619580e-07,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.634014,0.485339,0.621344,0.580232,0.067299,14
5,0.005010,0.000013,0.005002,2.996875e-06,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.629316,0.527290,0.607754,0.588120,0.043905,13
6,0.041062,0.012269,0.004336,9.440910e-04,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.633819,0.632780,0.684762,0.650454,0.024263,3
7,0.027107,0.001541,0.002101,1.639935e-03,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.678559,0.685113,0.665685,0.676452,0.008070,1
8,0.019459,0.001916,0.003668,9.424039e-04,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.649045,0.432880,0.618631,0.566852,0.095543,15
9,0.013336,0.002358,0.005003,2.247832e-07,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.580375,0.690020,0.552184,0.607526,0.059456,10
10,0.018343,0.002348,0.001667,2.357414e-03,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.421850,0.635362,0.631187,0.562800,0.099681,16
11,0.016681,0.002351,0.003332,2.356347e-03,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.623944,0.679287,0.580997,0.628076,0.040233,5
12,0.005000,0.000003,0.003335,2.358032e-03,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.548696,0.702686,0.629232,0.626871,0.062888,6
13,0.003334,0.002357,0.005002,1.189441e-06,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.561763,0.587323,0.639244,0.596110,0.032236,12
14,0.003333,0.002357,0.003335,2.358088e-03,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.575844,0.659364,0.655115,0.630108,0.038409,4
15,0.003334,0.002358,0.003334,2.357302e-03,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.600816,0.611981,0.580217,0.597671,0.013157,11
16,0.003337,0.002359,0.003334,2.357751e-03,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.612303,0.677260,0.287633,0.525732,0.170437,17
17,0.003333,0.002357,0.003334,2.357751e-03,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.659686,0.586255,0.596101,0.614014,0.032544,9

In [17]:
age=float(input("Age:"))
BMI=float(input("BMI:"))
children=int(input("Children:"))
sex=int(input("Male-1 or Female-0:"))
smoker=int(input("Yes-0 or No-1:"))

Age:45
BMI:15
Children:1
Male-1 or Female-0:1
Yes-0 or No-1:0

In [18]:
Future_charge_prediction=grid.predict([[age,BMI,children,sex,smoker]])
Future_charge_prediction
print("Future Prediction:{}".format(Future_charge_prediction))

Future Prediction:[48673.5588]