In [17]:
import pandas as pd

In [18]:
data=pd.read_csv("50_Startups.csv")
data

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [19]:
data=pd.get_dummies(data,drop_first=True)
data

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [20]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [21]:
indep=data[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]
indep

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.95        311613.29              0               1
9   123334.88       108679.17        304981.62              0               0
10  101913.08       110594.11        229160.95              1               0
11  100671.96        91790.61        249744.55              0               0
12   93863.75       127320.38        249839.44              1               0
13   91992.39       135495.07        252664.93              0               0
14  119943.24       156547.42        256512.92              1               0
15  114523.61       122616.84        261776.23              0               1
16   78013.11       121597.55        264346.06              0               0
17   94657.16       145077.58        282574.31              0               1
18   91749.16       114175.79        294919.57              1               0
19   86419.70       153514.11             0.00              0               1
20   76253.86       113867.30        298664.47              0               0
21   78389.47       153773.43        299737.29              0               1
22   73994.56       122782.75        303319.26              1               0
23   67532.53       105751.03        304768.73              1               0
24   77044.01        99281.34        140574.81              0               1
25   64664.71       139553.16        137962.62              0               0
26   75328.87       144135.98        134050.07              1               0
27   72107.60       127864.55        353183.81              0               1
28   66051.52       182645.56        118148.20              1               0
29   65605.48       153032.06        107138.38              0               1
30   61994.48       115641.28         91131.24              1               0
31   61136.38       152701.92         88218.23              0               1
32   63408.86       129219.61         46085.25              0               0
33   55493.95       103057.49        214634.81              1               0
34   46426.07       157693.92        210797.67              0               0
35   46014.02        85047.44        205517.64              0               1
36   28663.76       127056.21        201126.82              1               0
37   44069.95        51283.14        197029.42              0               0
38   20229.59        65947.93        185265.10              0               1
39   38558.51        82982.09        174999.30              0               0
40   28754.33       118546.05        172795.67              0               0
41   27892.92        84710.77        164470.71              1               0
42   23640.93        96189.63        148001.11              0               0
43   15505.73       127382.30         35534.17              0               1
44   22177.74       154806.14         28334.72              0               0
45    1000.23       124153.04          1903.93              0               1
46    1315.46       115816.21        297114.46              1               0
47       0.00       135426.92             0.00              0               0
48     542.05        51743.15             0.00              0               1
49       0.00       116983.80         45173.06              0               0

In [22]:
dep=data[['Profit']]
dep

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [25]:
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
x_train=scx.fit_transform(x_train)
x_test=scx.transform(x_test)

In [26]:
from sklearn.preprocessing import StandardScaler
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [35]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
param={'kernel':['linear','rbf','poly'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid=GridSearchCV(SVR(), param, refit=True, verbose=3, n_jobs=-1) 
grid.fit(x_train,y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)

Fitting 3 folds for each of 30 candidates, totalling 90 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   13.5s
[Parallel(n_jobs=-1)]: Done  52 out of  90 | elapsed:   14.5s remaining:   10.6s
[Parallel(n_jobs=-1)]: Done  90 out of  90 | elapsed:   17.3s finished
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                           epsilon=0.1, gamma='auto_deprecated', kernel='rbf',
                           max_iter=-1, shrinking=True, tol=0.001,
                           verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [42]:
result=grid.cv_results_
print("Best results{}:".format(grid.best_params_))

Best results{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}:

In [46]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.016671,0.006237,0.003333,0.004714,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.869262,0.917180,0.939078,0.907633,0.029100,9
1,0.008335,0.011788,0.001668,0.002358,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.626308,0.805007,0.764967,0.731155,0.077448,11
2,0.008334,0.008499,0.003334,0.002357,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",-1.028896,0.547306,0.240213,-0.089621,0.689755,21
3,0.008335,0.002360,0.000000,0.000000,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.869262,0.917180,0.939078,0.907633,0.029100,9
4,0.003010,0.002128,0.003340,0.002362,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.622057,0.812127,0.760184,0.730635,0.081200,16
5,0.003335,0.002358,0.000000,0.000000,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-1.117302,0.528628,0.281768,-0.113275,0.732081,22
6,0.048347,0.016500,0.001667,0.002358,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.869212,0.916993,0.939509,0.907687,0.029249,3
7,0.001670,0.002362,0.001665,0.002355,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.626308,0.805007,0.764967,0.731155,0.077448,11
8,0.008334,0.002358,0.005002,0.004084,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",-2.166847,0.582888,0.300455,-0.448643,1.246343,27
9,0.053346,0.008500,0.000000,0.000000,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.869212,0.916993,0.939509,0.907687,0.029249,3
10,0.003335,0.002358,0.003335,0.002358,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.622057,0.812127,0.760184,0.730635,0.081200,16
11,0.001667,0.002358,0.000000,0.000000,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",-2.164576,0.582667,0.300180,-0.448026,1.245155,23
12,0.425652,0.027373,0.003336,0.002359,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.868952,0.917108,0.939562,0.907654,0.029397,7
13,0.001668,0.002359,0.000000,0.000000,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.626308,0.805007,0.764967,0.731155,0.077448,11
14,0.015004,0.014145,0.000000,0.000000,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",-2.166847,0.582888,0.300455,-0.448643,1.246343,27
15,0.388815,0.157632,0.002172,0.002720,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.868952,0.917108,0.939562,0.907654,0.029397,7
16,0.003334,0.004716,0.001666,0.002356,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.622057,0.812127,0.760184,0.730635,0.081200,16
17,0.003335,0.002358,0.000000,0.000000,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",-2.164576,0.582667,0.300180,-0.448026,1.245155,23
18,0.385825,0.057810,0.000000,0.000000,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.868821,0.917290,0.939739,0.907727,0.029536,1
19,0.000000,0.000000,0.001504,0.002127,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.626308,0.805007,0.764967,0.731155,0.077448,11
20,0.001668,0.002359,0.000000,0.000000,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",-2.166847,0.582888,0.300455,-0.448643,1.246343,27
21,0.295097,0.033414,0.000000,0.000000,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.868821,0.917290,0.939739,0.907727,0.029536,1
22,0.000000,0.000000,0.001667,0.002358,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.622057,0.812127,0.760184,0.730635,0.081200,16
23,0.002171,0.002095,0.001668,0.002359,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",-2.164576,0.582667,0.300180,-0.448026,1.245155,23
24,0.546877,0.158448,0.001666,0.002356,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.868550,0.917143,0.939992,0.907663,0.029729,5
25,0.001666,0.002356,0.001672,0.002365,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.626308,0.805007,0.764967,0.731155,0.077448,11
26,0.001663,0.002352,0.000000,0.000000,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",-2.166847,0.582888,0.300455,-0.448643,1.246343,27
27,0.452698,0.206035,0.000000,0.000000,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.868550,0.917143,0.939992,0.907663,0.029729,5
28,0.000000,0.000000,0.001666,0.002357,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.622057,0.812127,0.760184,0.730635,0.081200,16
29,0.001668,0.002358,0.000000,0.000000,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",-2.164576,0.582667,0.300180,-0.448026,1.245155,23

In [49]:
y_pred=grid.predict(x_test)
from sklearn.metrics import r2_score
rscore=r2_score(y_test,y_pred)
rscore

0.9375289409802517

In [50]:
import pickle

In [51]:
filename=("Final_model.sav")

In [52]:
pickle.dump(grid,open(filename,'wb'))

In [53]:
Load=pickle.load(open("Final_model.sav",'rb'))

In [57]:
preinput=scx.transform([[10000,25000,85000,1,0]])
Predict=Load.predict(preinput)
Predict

array([-1.27469291])

In [61]:
preoutput=scy.inverse_transform(Predict)
preoutput

array([55397.25780504])